clear all;clc;

GrainYld = [1.1  .9  .8  .65];  %qtd em ton de qntos graos sao produzidos por grupo
GrainArea = [20 30 20 10]; %area de cada grupo para produzir graos
years = [1:5];
land_groups = [1:4];
cows_ages = [1:12]; %as vacas leiteiras ficam por 12 anos na fazenda antes de serem vendidas
s_cow_ages = [2:11];
max_accommodation = 130; %maximo de vacas que a fazenda consegue sustentar
grain_per_cow = .6; %cada vaca requer 0.6 ton de graos
sugar_beet_per_cow = .7; %cada vaca requer 0.7 tons de beterraba sacarina
acre_per_heifer = 2/3;%cada novilha precisa de 2/3 de acre
max_acre = 200;% a fazenda tem 200 acres
labour_per_heifer = 10; %horas de trabalho por novilho
labour_per_cow = 42;% horas de trabalho por vaca
labour_per_acre_to_grain = 4;%horas de trabalho por acre para produzir graos
labour_per_acre_to_sb = 14;%horas de trabalho por acre para produzir sugar beet
total_available_work = 5500;%total de horas de trabaljp
survivial_rate_cow = .98;%taxa de sobrevivencia de vacas
survivial_rate_heifer = .95; %taxa de sobrevivencia de novilhos
initial_heifers = 9.5
initial_cows = 9.8
new_heifers_per_cow = 1.1/2
min_end_total = 50
max_end_total = 175
num_bulldogs_per_cow = 1.1/2
price_selling_bulldogs = 30
price_selling_heifers = 40
price_selling_12year_old_cows = 120
price_selling_milk = 370
price_selling_grain = 75
price_selling_sugar_beet = 58
price_buying_grain = 90
price_buying_sugar_beet = 70
price_extra_labour = 120
heifer_costs = 50
cow_costs = 100
acre_grain_labour_cost = 15
acre_sb_labour_cost = 10
annual_loan_repayment = 39.71
available_labour_cost = 4000
capital_expenditures = 158.85